package com.bojanvilic.crvenazvezdainfo.theme

import androidx.compose.ui.graphics.Color

val light_theme_primary = Color(0xFFBE0001)
val light_theme_secondary = Color(0xFF800000)
val light_theme_tertiary = Color(0xFF800000)
val light_theme_error = Color(0xFFFFB4AB)
val light_theme_errorContainer = Color(0xFF93000A)
val light_theme_onError = Color(0xFF690005)
val light_theme_onErrorContainer = Color(0xFFFFDAD6)
val light_theme_background = Color(0xFFeeeeee)
val light_theme_onBackground = Color(0xFFeeeeee)
val light_theme_surfaceVariant = Color(0xFFFDF3F1)
val light_theme_onSurfaceVariant = Color(0xFF1b1b1b)

val dark_theme_primary = Color(0xFFBE0001)
val dark_theme_secondary = Color(0xFF800000)
val dark_theme_tertiary = Color(0xFFFFB3B4)
val dark_theme_error = Color(0xFFFFB4AB)
val dark_theme_errorContainer = Color(0xFF93000A)
val dark_theme_onError = Color(0xFF690005)
val dark_theme_onErrorContainer = Color(0xFFFFDAD6)
val dark_theme_background = Color(0xFF1b1b1b)
val dark_theme_onBackground = Color(0xFF1b1b1b)
val dark_theme_surfaceVariant = Color(0xFF424242)
val dark_theme_onSurfaceVariant = Color(0xFFefefef)

val dark_background = Color(0xFF424242)
val dark_onSurface = Color(0xFF1b1b1b)
val dark_inverseOnSurface = Color(0xFF1b1b1b)
val dark_onSurfaceVariant = Color(0xFFefefef)

val md_theme_dark_primary = Color(0xFFFFB3B4)
val md_theme_dark_onPrimary = Color(0xFF680016)
val md_theme_dark_primaryContainer = Color(0xFF920023)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFFcf12fc)
val md_theme_dark_onBackground = Color(0xFFECE0DF)
val md_theme_dark_surface = Color(0xFFcf12fc)
val md_theme_dark_onSurface = Color(0xFFECE0DF)
val md_theme_dark_surfaceVariant = Color(0xFF524343) // background card
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C1) //card text color
val md_theme_dark_outline = Color(0xFFA08C8C)
val md_theme_dark_inverseSurface = Color(0xFFECE0DF)
val md_theme_dark_inversePrimary = Color(0xFFBF0031)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B4)